# Generated by Django 4.1.3 on 2022-11-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='cancelled',
        ),
    ]
