# Generated by Django 4.1.3 on 2022-11-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
