# Generated by Django 4.1.3 on 2022-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_classinstance_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='cancel_all_future',
            field=models.BooleanField(default=False, verbose_name='Cancel all Future Classes'),
        ),
    ]
