# Generated by Django 4.1.3 on 2022-11-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_class_cancel_all_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.class', verbose_name='Class Name'),
        ),
    ]
